name: Build installer for supported os
on: push

jobs:
  build-app:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew :app:package
      - run: mkdir staging && cp app/build/installer/* staging
        shell: bash
      - name: upload build result
        uses: actions/upload-artifact@v7
        with:
          name: Fourier-${{ matrix.os }}
          path: staging
